name: gradient_colored_slider
description: Gradient Colored Slider
version: 1.0.0+1
homepage: https://github.com/kirn-tech/gradient_colored_slider

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


